/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const showDialog: typeof import('vant/es')['showDialog']
  const showImagePreview: typeof import('vant/es')['showImagePreview']
  const showNotify: typeof import('vant/es')['showNotify']
}
